In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 50)

df = pd.read_parquet("../data/reto.parquet")

df.head()

,id,attachments,author,authorCategory,authorCategoryId,authorId,authorURL,automateProjectId,caption,context,contextTitle,country,createdAt,description,engagementRate,facebookAdAccountId,facebookIds,facebookMessengerThreadId,facebookPageId,group,hasImageOrVideo,host,ignored,image,influenceScore,...,metadata,minRating,parentCreatedAt,parentId,parentText,places,preciseId,private,rating,recipients,sentiment,sex,socialType,sourceData,sourceId,sourceLimitations,sourceName,sourceURL,tags,text,threadId,title,type,url,youtubeChannelId
0,c6adb4630994bdee807d387382d526bc,[],Consulta Popular,,,,,,,El camino hacia la consulta popular en Colombia,,co,1750834500000,,,,[],,,portal,False,www.proclamadelpacifico.com,False,,1,...,,,,,,[],es_1750834500000_c6adb4630994bdee807d387382d526bc,False,,[],UNKNOWN,u,,,,[],,https://www.proclamadelpacifico.com/el-camino-...,[],Hasta 1990 el C&oacute;digo Sustantivo del Tra...,c6f5b8840e9675c607bc42a16543c1d72ef4f771759834...,El camino hacia la consulta popular en Colombia,ar,https://www.proclamadelpacifico.com/el-camino-...,
1,9fee3686bd7f2fd45d381a9b388dfb5e,[],Consulta Popular,,,,,,,La Consulta popular constituyente,,co,1750836300000,,,,[],,,portal,False,www.proclamadelpacifico.com,False,,1,...,,,,,,[],es_1750836300000_9fee3686bd7f2fd45d381a9b388dfb5e,False,,[],UNKNOWN,u,,,,[],,https://www.proclamadelpacifico.com/la-consult...,[],La Consulta popular constituyente/El deliberad...,f565efdfc7bd00275467b1e2d8e90036f986e5e50d1896...,La Consulta popular constituyente,ar,https://www.proclamadelpacifico.com/la-consult...,
2,9adb9324d96a398905767afcf428e956,[],Daniel Hernandez,,,,,,,"Empleo juvenil, frente del mercado laboral que...",,co,1750837740000,,,,[],,,portal,False,www.portafolio.co,False,,4,...,,,,,,[],es-co_1750837740000_9adb9324d96a398905767afcf4...,False,,[],UNKNOWN,m,,,,[],,https://www.portafolio.co/economia/empleo/refo...,[],En medio de la expectativa por lo que vendr&aa...,3d97a4b17c73e05726d2a10e10edf6a653cfa03053e7ca...,"Empleo juvenil, frente del mercado laboral que...",ar,https://www.portafolio.co/economia/empleo/refo...,
3,be6ed61346de9fc96e3e797d70d275a9,[],,,,,,,,Petro da marcha atrás con consulta sobre <q>re...,,mx,1750840406000,,,,[],,,portal,False,www.eleconomista.com.mx,False,,4,...,,,,,,[],es-mx_1750840406000_be6ed61346de9fc96e3e797d70...,False,,[],UNKNOWN,u,,,,[],,https://www.eleconomista.com.mx/internacionale...,[],El Senado tampoco autoriz&oacute; a mediados d...,1e19407566ce89c0a86e50c86633f8ccf07ccfdb9e60c2...,Petro da marcha atr&aacute;s con consulta sobr...,ar,https://www.eleconomista.com.mx/internacionale...,
4,4a893f2667aa8eddb4c84fcd09fcd43f,[],,,,,,,,Petro firmó decreto de la <q>reforma</q> <q>la...,,co,1750848960000,,,,[],,,portal,False,www.kienyke.com,False,,3,...,,,,,,[],es_1750848960000_4a893f2667aa8eddb4c84fcd09fcd43f,False,,[],UNKNOWN,u,,,,[],,https://www.kienyke.com/politica/gustavo-petro...,[],Cr&eacute;ditos: X @infopresidencia El preside...,f689aa9604212e6e350dbfb942bc3579f07871b5f8b547...,Petro firm&oacute; decreto de la <q>reforma</q...,ar,https://www.kienyke.com/politica/gustavo-petro...,

In [ ]:
df[df["id"] == "tikapi_7520805329748151557"]

,id,attachments,author,authorCategory,authorCategoryId,authorId,authorURL,automateProjectId,caption,context,contextTitle,country,createdAt,description,engagementRate,facebookAdAccountId,facebookIds,facebookMessengerThreadId,facebookPageId,group,hasImageOrVideo,host,ignored,image,influenceScore,...,metadata,minRating,parentCreatedAt,parentId,parentText,places,preciseId,private,rating,recipients,sentiment,sex,socialType,sourceData,sourceId,sourceLimitations,sourceName,sourceURL,tags,text,threadId,title,type,url,youtubeChannelId
930,tikapi_7520805329748151557,[{'name': 'https://v45-eu.tiktokcdn.com/962e6e...,FRANK PORTILLA (@frankportilla0),,,6812248190717543430,,,,,,,1751073950000,,84.85,,[],,,tiktok,True,www.tiktok.com,False,https://sentione.com/app/assets/statements?sta...,10,...,,,,,,[],es_1751073950000_tikapi_7520805329748151557,False,,[],NEUTRAL,m,tiktokVideo,,,[],,https://www.tiktok.com/@frankportilla0/video/7...,[],🚨EL GUERRILLERO PETRO <q>ELIMIN&Oacute;</q> LO...,tikapi_7520805329748151557,,st,https://www.tiktok.com/@frankportilla0/video/7...,